### ISSUE TITLE
spawn ENOENT

### ISSUE THREAD

**Issue by samirlegdah** [sina-masnadi/lambda-ghostscript#3]
hi,
great job... but how can i use this binari ?

i tried with https://github.com/sina-masnadi/node-gs 

```
              gs()
                .batch()
                .nopause()
                .option('-r' + 50 * 2)
                .option('-dDownScaleFactor=2')
                .executablePath()
                .device('png16m')
                .output(tempNewPath)
                .input(tempFilePath)
                .exec( (err, stdout, stderr) =>{
                    if (!err) {
                        console.log('gs executed w/o error');
                        console.log('stdout', stdout);
                        console.log('stderr', stderr);
                        //resolve();
                        return true
                    } else {
                        console.log('gs error:', err);
                        //reject(err);
                        return false
                    }
                });
        
```

but i have this error:
```

Error: spawn ../lambda-ghostscript/bin/gs ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I thought the problem was the gs module, so I tried calling the binary file directly with spawn
```
var path = require('path')
const { spawn } = require('child_process');

var opz = ["-dBATCH","-dNOPAUSE","-r100","-dDownScaleFactor=2","-sDEVICE=png16m","-sOutputFile=/tmp/1-Introduzione_2018.png","/dist/in.pdf"];

var nwDir = path.dirname(process.execPath);
var a = path.join(__dirname,"lambda-ghostscript","bin","gs")
spawn(a, opz).stdout.on("data", function(d) {
    console.log(d);
  });
```
BUT
```

Error: spawn c:\Users\Samir\Documents\GitHub\esempi\provaGs\lambda-ghostscript\bin\gs ENOENT
util.js:1024
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

what am I doing wrong??  thanks

**Comment by mcodina86** [comment]
Try using exec instead spawn. [See more here](https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a)

**Comment by Codezhak** [comment]
@samirlegdah Do you find the solution? I am also got stuck on this. Any suggestion would be appreciated.

**Comment by Codezhak** [comment]
Solved my issue. It was just a permission issue!!. I added complete permission (r, w, x) using Linux OS and then uploaded to lambda, worked for me.

**Comment by adwaitpatankar** [comment]
Using the node-gs wrapper and the compiled ghostscript for generating the pdf report. We are able to generate a pdf report when executed on a linux machine. However when executed as part of the AWS lambda function not getting any output. No errors, but not getting in any of the below blocks when added loggers.

proc.stdout.on('data', function (data) {
                totalBytes += data.length;
                _data.push(data);
            });
            proc.on('close', function () {
                var buf = Buffer.concat(_data, totalBytes);

                return cb.call(self, null, buf.toString());
            });
            process.on('exit', function () {
                proc.kill();
            });

**Comment by brunokunace** [comment]
@Codezhak i cant test it, you can send a example working with node and gs? only simple example, i can try here and receive errors

**Comment by brunokunace** [comment]
you can help @sina-masnadi ?

index.js on lambda
```
exports.handler = async (event) => {
var gs = require('gs');
gs()
    .batch()
    .nopause()
    .option('-r' + 50 * 2)
    .option('-dDownScaleFactor=2')
    .executablePath('/var/tasks/ghostscript/bin/gs')
    .device('png16m')
    .output('tmp/123.png')
    .input('tmp/123.pdf')
    .exec(function (err, stdout, stderr) {
        if (!err) {
		   // no error
		   console.log('no errors')
        } else {
		   // handle errors
		   console.log('deu merda')
        }
	});
};
```
![image](https://user-images.githubusercontent.com/16597320/61146047-6a3b1600-a4af-11e9-8d72-ab86c626dff2.png)

ghostscript folder, downloaded here https://github.com/sina-masnadi/lambda-ghostscript

**Comment by brunokunace** [comment]
the console error:

```
INFO	gs command: -dBATCH,-dNOPAUSE,-r100,-dDownScaleFactor=2,-sDEVICE=png16m,-sOutputFile=tmp/123.png,tmp/123.pdf
ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"spawn /var/tasks/ghostscript/bin/gs ENOENT","code":"ENOENT","stack":["Error: spawn /var/tasks/ghostscript/bin/gs ENOENT","    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)","    at onErrorNT (internal/child_process.js:415:16)","    at process._tickCallback (internal/process/next_tick.js:63:19)"],"errno":"ENOENT","syscall":"spawn /var/tasks/ghostscript/bin/gs","path":"/var/tasks/ghostscript/bin/gs","spawnargs":["-dBATCH","-dNOPAUSE","-r100","-dDownScaleFactor=2","-sDEVICE=png16m","-sOutputFile=tmp/123.png","tmp/123.pdf"]}
```

when i remove /var/taks and put only: executablePath('ghostscript/bin/gs') i receive it

```
INFO	gs command: -dBATCH,-dNOPAUSE,-r100,-dDownScaleFactor=2,-sDEVICE=png16m,-sOutputFile=tmp/123.png,tmp/123.pdf
ERROR	Invoke Error	{"errorType":"TypeError","errorMessage":"Cannot read property 'on' of undefined","stack":["TypeError: Cannot read property 'on' of undefined","    at Object.exec (/var/task/node_modules/gs/index.js:91:24)","    at Runtime.exports.handler (/var/task/index.js:34:6)","    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
2019-07-12T17:25:14.142Z	bb5844cd-6d2f-4eb7-9b48-1e81e2b2fbbb	ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"spawn ghostscript/bin/gs EACCES","code":"EACCES","stack":["Error: spawn ghostscript/bin/gs EACCES","    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)","    at onErrorNT (internal/child_process.js:415:16)","    at process._tickCallback (internal/process/next_tick.js:63:19)"],"errno":"EACCES","syscall":"spawn ghostscript/bin/gs","path":"ghostscript/bin/gs","spawnargs":["-dBATCH","-dNOPAUSE","-r100","-dDownScaleFactor=2","-sDEVICE=png16m","-sOutputFile=tmp/123.png","tmp/123.pdf"]}

```

**Comment by Codezhak** [comment]
Actually what solved my issue is I Just added execution permission for the entire files from Linux system and uploaded to lambda.
While I uploaded from Windows this ENOENT occurs.

**Comment by brunokunace** [comment]
> Actually what solved my issue is I Just added execution permission for the entire files from Linux system and uploaded to lambda.
> While I uploaded from Windows this ENOENT occurs.

FINE! you have a example on gist.github.com or repository working?

what version of node you run on lambda? 10?

thanks so much

**Comment by Codezhak** [comment]
I tested with the sample code given in the readme.
My node version is 10 on lambda.

**Comment by n123456789k** [comment]
@Codezhak @brunokunace did you find what was causing this error, running it on lambda and it's throwing this:
```
Error: spawn gs ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by brunokunace** [comment]
@narwy i solve this change permissions of folders before send it to lambda,  on windows i cant fiz it, only in mac or linux, for chmod method

**Comment by n123456789k** [comment]
@brunokunace it’s just recently happened the function hasn’t been updated for 9 months on lambda and is throwing this error. Is your lambda function still working can you share your function please ?

**Comment by adwaitpatankar** [comment]
It has worked in my case too with following things:

- Have to give execute permissions on the "gs" executable on a linux machine.
- Build the lambda function zip on the linux machien and update the lambda function using the aws command line.

Another thing I had tried was I had to make use of spawnsync instead of spawn as in, my requirement was to generate the pdf report and send it back as response to the API Gateway.

**Comment by adwaitpatankar** [comment]
There is definitely tight coupling with Linux. If you download the GS and wrapper code from github on to windows machine and try pushing to the lambda, you are bound to get the execution permission issues.

**Comment by Codezhak** [comment]
@narwy Actually the problem can be solved by using chmod in linux and zip and update from the linux machine. But you said lambda has not been updated for last 9 months. So it is a guess that do you upgraded the lambda node version recently. Also can you share which node version you are using currently.

**Comment by RicardoElSabio** [comment]
@Codezhak @adwaitpatankar  I am facing the same issue, i am getting spawn EACCESS at child process.  I am using windows, Vscode. So i have no idea how to do that chmod, I am new to this
this is my cloud function:

    exports.generateThumbnail = functions.storage.object().onFinalize(async (object) => {
    const filePath = object.name // file path in the bucket 
    console.log('file path', filePath);

    const fileBucket = object.bucket; // file bucket name
    console.log('file Bucket', fileBucket);

    const fileName = path.basename(filePath); // file name 
    console.log('file name', fileName);

    const contentType = object.contentType; // file content Type;
    console.log('content type', contentType);

    const tempFilePath = path.join(os.tmpdir(), fileName);// temp file path
    console.log('temp file path', tempFilePath);

    const metageneration = object.metageneration; // Number of times metadata has been generated. New objects have a value of 1
    // Get the file name

    const imageName = path.basename(filePath, '.pdf') + '.png' // image Name 
    console.log('image name ', imageName);

    const imageFilePath = path.join(path.dirname(filePath), imageName); // image file path
    console.log('image file path', imageFilePath);

    const bucket = gcs.bucket(fileBucket); //
    console.log('bucket ', bucket);
    const metadata = {
        contentType: contentType,
    }
    console.log('meta data', metadata);

    if (fileName.endsWith('.png')) return false;
    if (!fileName.endsWith('.pdf')) return false;

    await bucket.file(filePath).download({ destination: tempFilePath });
    console.log('Image downloaded localy to ', tempFilePath);

    await new Promise((resolve, reject) => {
        gs()
            .batch()
            .nopause()
            .option('-r' + 50 * 2)
            .option('-dDownScaleFactor=2')
            .executablePath('lambda-ghostscript/bin/./gs')
            .device('png16m')
            .output(imageFilePath)
            .input(tempFilePath)
            .exec(function (err, stdout, stderr) {
                if (!err) {
                    console.log('gs executed w/o error');
                    console.log('stdout', stdout);
                    console.log('stderr', stderr);
                    resolve();
                } else {
                    console.log('gs error:', err);
                    reject(err);
                }
            });
    }).then(async () => {
        // uploading the image 
        await bucket.upload(tempFilePath, {
            destination: imageFilePath,
            metadata: metadata,
        });

        // 
        return fs.unlinkSync(tempFilePath);
    })
});

**Comment by musso** [comment]
> @narwy i solve this change permissions of folders before send it to lambda, on windows i cant fiz it, only in mac or linux, for chmod method

Can you list your solution here ? is it `chmod -R u+x lambda-ghostscript `?

**Comment by tindoantrong** [comment]
I got the same issue on window

**Comment by tindoantrong** [comment]
Go to node_modules\gs\index.js add param: {shell: true} at line 86 and line 88.
My problem on windows was solved.

hope that help

**Comment by maurice-ellis** [comment]
If anyone every comes here again, here is how I solved this error. I'm just getting into Lambda, so I'm thinking the executable paths may have been different previously, but  anyways, AWS exports layer content to `/opt`, so the correct path for Ghostscript is the following:
```
/opt/bin/gs
```
